#DEFINIDO PROPRIEDADES DA NOSSA APLICACAO
#CONFIGURA\u00c3\u0087\u00c3\u0095ES DO BANCO DE DADOS
#DEFINICAO DE REGRA DO JPA
spring.application.name=cliente_api
spring.datasource.url=jdbc:postgresql://localhost:5432/cliente_api
spring.datasource.username=postgres
spring.datasource.password=lu1617
spring.datasource.driver-class-name=org.postgresql.Driver
#AQUI DEFINIMOS NOSSA CONFIGURACAO DO JPA, HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true